version: "3"
services:

  mopidy:
    image: 'ghcr.io/mcb/streaming-audio-snapserver:latest'
    ports:
        - "6680:6680"
        - "6681:6681"
        - "16600:6600"
    volumes:
        - fifo:/fifo/
        - ./mopidy/mopidy.conf:/etc/mopidy.conf
    restart: unless-stopped

  snapserver:
    image: 'ghcr.io/mcb/streaming-audio-snapserver:latest'
    ports:
      - "1704:1704"
      - "1705:1705"
      - "1780:1780"
    environment:
      - SERVICE_NAME=Snapcast  # for Avahi container
      - SERVICE_PORT=1704  # for Avahi container
      - SERVICE_TYPE=_snapcast._tcp  # for Avahi container
    volumes:
        - ./snapserver/snapserver.conf:/etc/snapserver.conf
        - fifo:/fifo/
    restart: unless-stopped


  shairport:
    image: 'docker.io/mikebrady/shairport-sync'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - fifo:/fifo
    # Needs network_mode:host as per https://github.com/mikebrady/shairport-sync-docker/issues/16
    network_mode: host 
    command:
      - -a
      - "Streaming Audio"
      - -o
      - pipe
      - --
      - /fifo/snapfifo.shairport
    restart: unless-stopped

volumes:
  fifo:

networks:
  snapcast:
