version: "3"
services:

  mopidy:
    #image:
    build: ./mopidy
    ports:
        - "6680:6680"
        - "6681:6681"
        - "16600:6600"
    volumes:
        - fifo:/fifo/
        - ./mopidy/mopidy.conf:/etc/mopidy.conf
    networks:
        - snapcast
    restart: unless-stopped

  snapserver:
    build: ./snapserver
    ports:
      - "1704:1704"
      - "1705:1705"
    environment:
      - SERVICE_NAME=Snapcast  # for Avahi container
      - SERVICE_PORT=1704  # for Avahi container
      - SERVICE_TYPE=_snapcast._tcp  # for Avahi container
    volumes:
        - ./snapserver/snapserver.conf:/etc/snapserver.conf
        - fifo:/fifo/
    networks:
      - snapcast
    restart: unless-stopped


  shairport:
    #image: 'docker.io/kevineye/shairport-sync'
    build: ./shairport
    environment:
      - AIRPLAY_NAME=StreamingAudio
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - fifo:/fifo
    command:
      - -p
      - "5001"
      - -o
      - pipe
      - --
      - /fifo/snapfifo.shairport
    networks:
      - snapcast
    restart: unless-stopped

volumes:
  fifo:

networks:
  snapcast:
