version: "3"
services:

  mopidy:
    #image:
    build: ./mopidy
    ports:
        - "6680:6680"
        - "6681:6681"
        - "16600:6600"
    volumes:
        - fifo:/fifo/
        - ./mopidy/mopidy.conf:/etc/mopidy.conf
    restart: unless-stopped

  snapserver:
    build: ./snapserver
    ports:
      - "1704:1704"
      - "1705:1705"
      - "1780:1780"
    environment:
      - SERVICE_NAME=Snapcast  # for Avahi container
      - SERVICE_PORT=1704  # for Avahi container
      - SERVICE_TYPE=_snapcast._tcp  # for Avahi container
    volumes:
        - ./snapserver/snapserver.conf:/etc/snapserver.conf
        - fifo:/fifo/
    restart: unless-stopped


  shairport:
    image: 'docker.io/mikebrady/shairport-sync'
    # build: ./shairport
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - fifo:/fifo
    ports:
      # AirPlay ports
      #- '3689:3689'
      #- '5000:5000'
      #- '6000-6009:6000-6009/udp'
      # AirPlay-2 ports
      - '319-320:319-320/udp'
      - '3689:3689'
      - '5000:5000'
      - '7000:7000'
      - '6000-6009:6000-6009/udp'
      # Avahi ports
      - '5353:5353'
    command:
      - -a
      - "StreamingAudio"
      - -o
      - pipe
      - --
      - /fifo/snapfifo.shairport
    restart: unless-stopped

volumes:
  fifo:

networks:
  snapcast:
